; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Burn fuses once after first flash: pio run -t fuses -e ATtiny402
[env:ATtiny402]
platform = atmelmegaavr
board = ATtiny402
framework = arduino
build_flags = -DLOAD_PROFILE_INCANDESCENT
board_hardware.bod = 4.3v
upload_protocol = serialupdi
upload_port = /dev/cu.usbserial-110
upload_speed = 57600

[env:ATtiny402_LED]
extends = env:ATtiny402
build_flags = -DLOAD_PROFILE_LED
